version: 2
updates:
  # https://docs.github.com/cn/code-security/supply-chain-security/keeping-your-dependencies-updated-automatically/configuration-options-for-dependency-updates
  # Maintain dependencies for npm

  # Maintain dependencies for GitHub Actions
  - package-ecosystem: github-actions
    # Workflow files stored in the
    # default location of `.github/workflows`
    directory: "/"
    schedule:
      # Check for updates to GitHub Actions every weekday
      interval: daily
      time: "02:00"
    open-pull-requests-limit: 20
    labels:
      - "github-actions"
    commit-message:
      prefix: "github-actions"
