name: Gitee

on:
  workflow_dispatch:
  push:
    branches:
      - main

env:
  TZ: Asia/Shanghai

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Mirror the GitHub repos to Gitee
        uses: Yikun/hub-mirror-action@master
        with:
          src: github/JaimeZeng
          dst: gitee/hellozxj
          dst_key: ${{ secrets.GITEE_PRIVATE_KEY }}
          dst_token: ${{ secrets.GITEE_TOKEN }}
          account_type: user
          clone_style: "ssh"
          static_list: "JaimeZeng.github.io"
          timeout: 300
          mappings: "JaimeZeng.github.io=>hellozxj"
          # force_update: true
